parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\ApiResource\Controller\:
        resource: "../src/ApiResource/Controller/"
        tags: ["controller.service_arguments"]

    App\Decorator\JwtDecorator:
        decorates: "api_platform.openapi.factory"

    App\Subscriber\UserSubscriber:
        tags: 
            - {name: doctrine.event_subscriber, connection: default}
