parameters:
    gasPriceYearUrl: "%env(GAS_PRICE_YEAR_URL)%"
    gasPriceInstantUrl: "%env(GAS_PRICE_INSTANT_URL)%"
    apiAddressUrl: "%env(API_ADDRESS_URL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $gasPriceYearUrl: "%gasPriceYearUrl%"
            $gasPriceInstantUrl: "%gasPriceInstantUrl%"
            $apiAddressUrl: "%apiAddressUrl%"

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\ApiResource\Controller\:
        resource: "../src/ApiResource/Controller/"
        tags: ["controller.service_arguments"]

    App\Decorator\JwtDecorator:
        decorates: "api_platform.openapi.factory"

    App\Subscriber\UserSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Subscriber\GasStationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
